### ISSUE TITLE
Find and Replace don't do anything

### ISSUE THREAD

**Issue by loopernow** [textadventures/squiffy-editor#12]
The menu options and the keyboard shortcuts do nothing in OS X El Capitan.

**Comment by papadasoft** [comment]
Hello looper, the last versión of Squiffy solved this issue but unfortunately it is not available for OSX.

**Comment by alexwarren** [comment]
Closing this issue as merging the `squiffy-editor` repo into the `squiffy` one.

My new update will fix the find/replace issue.
