### ISSUE TITLE
Will No Longer Run on Linux - Need to Update Electron to 4.2.12

### ISSUE THREAD

**Issue by KVonGit** [textadventures/squiffy-editor#19]
Recently, I found that I couldn't run the Squiffy editor in any recent version of any flavor of Linux.  It worked on Windows 10, but running it on Linux was a bust.

So, after doing some research, I found that we could update Electron from version 1.8.1 to version 4.2.12 to fix this issue.  I have tested my fix in all the flavors of Linux except Gentoo and Debian, and it works.

I do not have a Mac, though.  So, I'm hoping someone will spend 30 minutes (or less) building the Squiffy editor on a Mac using the source code from [my fork](https://github.com/KVonGit/squiffy-editor) on GitHub to see if everything works.

There were two issues.

1. On Windows and Linux, jquery was not being copied into the proper place in the build.  I fixed this by editing "gulpfile.js".
2. On Linux, there was a Pango error which said the Harfbuzz version was too old.  This was a bug in Electron, and it was fixed in version 4.x.x. So, I updated the Electron version from 1.8.1 to 4.2.12.  This works on Windows and on Linux.  I edited "gulpfile.js" and "package.json" to update the version of Electron.

---
I want to create a pull request so this gets updated in the real version of the Squiffy editor, but I want to make sure it doesn't introduce any issues for Mac users before I do it.

**Comment by Baltasarq** [comment]
> 

Hi,

> Recently, I found that I couldn't run the Squiffy editor in any
> recent version of any flavor of Linux. It worked on Windows 10, but
> running it on Linux was a bust.
> So, after doing some research, I found that we could update Electron
> from version 1.8.1 to version 4.2.12 to fix this issue. I have tested
> my fix in all the flavors of Linux except Gentoo and Debian, and it
> works.

Good work.
The electron version had not been updated for a long time.
Unfortunately, I cannot test that in a mac, so bad luck here. :-(

Hope someone else can do it.

-- Baltasar

**Comment by KVonGit** [comment]
I asked on the forum, but no one ever replied.

https://textadventures.co.uk/forum/squiffy/topic/qqqgxcfegkohodbk-xwyhw/attention-mac-users-who-have-the-time-to-build-squiffy-from-the-source-code

I'm half tempted to say just update it and see if any Mac users have issues, but most Linux users can probably get it running on their own. It works fine in Windows.

---
Also, I found that updating above a certain version of Electron will break the build.  I didn't take good notes concerning this, but I ended up using Electron 4.2.12.  That one definitely works on Windows and Linux.

**Comment by Baltasarq** [comment]
Hi,

> I asked on the forum, but no one ever replied.
> I'm half tempted to say just update it and see if any Mac users have
> issues, but most Linux users can probably get it running on their
> own. It works fine in Windows.

I'd do exactly day. Update and see what happens (probably nothing).


-- Baltasar

**Comment by dajix350** [comment]
@KVonGit Did you ever get it working with a new electron version? This seems like a good piece of software, but it is useless if it isn't updated. ~~This is exactly why Electron needs to die and why we need alternatives that use a system browser~~.

**Comment by alexwarren** [comment]
Closing this as I am moving the `squiffy-editor` repo into the main `squiffy` one.

Regarding this specific problem, this will be addressed when the next version is released.
