### ISSUE TITLE
UTF-8 not working in osx or windows

### ISSUE THREAD

**Issue by svenblum** [textadventures/squiffy-editor#6]
öäü and other UTF-8 chars are not transleted correctly when pressing the build-button. It's working in the web-version but not in windows or osx. the output is something like: Ã¶Ã¤Ã¼

**Comment by svenblum** [comment]
https://github.com/textadventures/squiffy-editor/releases/download/v4.0/Squiffy.4.0.Windows.exe

I'm sorry - the one above does not work!

**Comment by alexwarren** [comment]
This is fixed in the code so it will be part of the next release, Squiffy 5.

**Comment by svenblum** [comment]
thank you very much! I'll wait for the next release then...
